# Generated by Django 3.0.5 on 2020-04-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progress_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='rating',
        ),
        migrations.AlterField(
            model_name='progress',
            name='completion',
            field=models.IntegerField(choices=[(1, 'True'), (2, 'False')], default=2),
        ),
    ]
