# Generated by Django 3.0.5 on 2020-04-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_auto_20200425_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completion',
            field=models.IntegerField(blank=True, choices=[(1, 'True'), (2, 'False')], default=2, null=True),
        ),
    ]
