# Generated by Django 3.0.5 on 2020-04-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20200425_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completion',
            field=models.IntegerField(choices=[(1, 'True'), (2, 'False')], default=2),
        ),
    ]
