# Generated by Django 3.0.5 on 2020-04-26 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0017_remove_lecture_course'),
        ('progress', '0005_auto_20200425_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progress',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='course.Lecture'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('lecture', 'student')},
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
    ]
