# Generated by Django 3.0.5 on 2020-04-23 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_auto_20200423_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrol_date', models.DateTimeField(auto_now_add=True)),
                ('completion', models.IntegerField()),
                ('enrol', models.ManyToManyField(blank=True, through='course.Course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='enrolment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Enrol'),
            preserve_default=False,
        ),
    ]
