# Generated by Django 3.0.5 on 2020-04-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200423_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrolment',
        ),
        migrations.DeleteModel(
            name='Enrol',
        ),
    ]
