# Generated by Django 3.0.5 on 2020-04-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20200425_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='author',
        ),
    ]
