# Generated by Django 3.0.5 on 2020-04-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_lecture_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
    ]
