# Generated by Django 3.0.5 on 2020-04-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200424_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
