# Generated by Django 3.0.5 on 2020-04-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200424_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='timestamp',
        ),
    ]
