# Generated by Django 3.0.5 on 2020-04-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_type_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
