# Generated by Django 3.0.5 on 2020-04-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200424_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
