# Generated by Django 3.0.5 on 2020-04-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_userprofile_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
