# Generated by Django 3.0.5 on 2020-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0002_enrolment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='course',
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='completion',
            field=models.IntegerField(),
        ),
    ]
