# Generated by Django 3.0.5 on 2020-04-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200423_1156'),
        ('enrolment', '0003_auto_20200423_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
    ]
