# Generated by Django 3.0.5 on 2020-04-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0005_auto_20200423_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrol',
        ),
    ]
