# Generated by Django 3.0.5 on 2020-04-23 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200423_1307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrolment', '0006_delete_enrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
