# Generated by Django 3.0.5 on 2020-04-23 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_auto_20200423_1307'),
        ('enrolment', '0007_auto_20200423_1345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together={('course', 'user')},
        ),
    ]
