# Generated by Django 3.0.5 on 2020-04-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0009_enrolment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='rating',
        ),
    ]
