# Generated by Django 3.0.5 on 2020-04-25 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0013_auto_20200425_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='completion',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
